# Generated by Django 3.1.6 on 2021-02-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('places_count', models.IntegerField()),
                ('room_type', models.CharField(choices=[(1, 'індивідуальний'), (2, 'груповий')], default=2, max_length=2)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(default='UAH', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_start_studying', models.DateTimeField()),
                ('parent_phone', models.CharField(max_length=13)),
                ('parent_first_name', models.CharField(max_length=50)),
                ('parent_last_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lessons_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_release', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('lessons_type', models.CharField(choices=[(1, 'індивідуальне'), (2, 'групове')], max_length=2)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.classroom')),
                ('students', models.ManyToManyField(to='schedule.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_when_should_pay', models.DateField()),
                ('status', models.CharField(choices=[(1, 'оплачено'), (2, 'очікуємо оплати'), (3, 'закрито'), (4, 'тестове заняття')], max_length=2)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.service')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.student')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('students', models.ManyToManyField(to='schedule.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.teacher')),
            ],
        ),
    ]
