# Generated by Django 3.1.6 on 2021-02-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210209_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='places_count',
            field=models.IntegerField(blank=True),
        ),
    ]
