# Generated by Django 3.1.6 on 2021-02-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20210209_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='places_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
