# Generated by Django 3.1.6 on 2021-02-09 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20210209_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_test_lessons',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_start_studying',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lessons_duration',
            field=models.DurationField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_release',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
