# Generated by Django 3.1.6 on 2021-02-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20210209_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_start_studying',
            field=models.DateTimeField(blank=True),
        ),
    ]
