# Generated by Django 3.1.6 on 2021-02-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20210209_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='lessons_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
