# Generated by Django 3.1.6 on 2021-02-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_service_lessons_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='schedule.Subject'),
        ),
    ]
