# Generated by Django 3.1.6 on 2021-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_group_age_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='age_from',
            field=models.IntegerField(default=0),
        ),
    ]
