# Generated by Django 3.1.6 on 2021-02-09 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20210209_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Аудиторії', 'verbose_name_plural': 'Аудиторії'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Групи', 'verbose_name_plural': 'Групи'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Рахунки', 'verbose_name_plural': 'Рахунки'},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name': 'Заняття', 'verbose_name_plural': 'Заняття'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Послуги', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Учні', 'verbose_name_plural': 'Учні'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмети', 'verbose_name_plural': 'Предмети'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Викладачі', 'verbose_name_plural': 'Викладачі'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='schedule.Subject', verbose_name='Предмети'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Додатково'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва аудиторії'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='places_count',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='К-сть місць'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_type',
            field=models.CharField(choices=[('1', 'індивідуальний'), ('2', 'груповий')], default='2', max_length=2, verbose_name='Тип аудиторії'),
        ),
        migrations.AlterField(
            model_name='group',
            name='age_from',
            field=models.IntegerField(default=0, verbose_name='Вік з'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Назва групи'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='schedule.Student', verbose_name='Учні'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.teacher', verbose_name='Викладач'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_when_should_pay',
            field=models.DateField(verbose_name='Дата до якої здійснити оплату'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Унікальний номер рахунку'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.teacher', verbose_name='Отримувач'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.service', verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('1', 'оплачено'), ('2', 'очікуємо оплати'), ('3', 'закрито'), ('4', 'тестове заняття')], max_length=2, verbose_name='Статус рахунку'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.classroom', verbose_name='Аудиторія'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateField(verbose_name='Дата заняття'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='lessons_type',
            field=models.CharField(choices=[('1', 'індивідуальне'), ('2', 'групове')], max_length=2, verbose_name='Тип заняття'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.teacher', verbose_name='Викладач'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='time_end',
            field=models.TimeField(verbose_name='Час закінчення'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='time_start',
            field=models.TimeField(verbose_name='Час початку'),
        ),
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(default='UAH', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='service',
            name='lessons_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='К-сть занять'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва послуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_start_studying',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата старту навчання'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_test_lessons',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата тестового заняття'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Імʼя одного з батьків'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Прізвище одного з батьків'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефону батьків'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lessons_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Тривалість заняття'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва предмету'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_release',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата звільнення'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефону'),
        ),
    ]
