# Generated by Django 3.1.6 on 2021-02-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20210209_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('1', 'активний'), ('2', 'відпустка'), ('3', 'неактивний')], default='1', max_length=2, verbose_name='Статус'),
        ),
    ]
