# Generated by Django 3.1.6 on 2021-02-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20210209_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receiver_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.teacher', verbose_name='Вчитель'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='receiver',
            field=models.CharField(blank=True, choices=[('1', 'Школа'), ('2', 'Вчитель')], default='1', max_length=2, null=True, verbose_name='Отримувач'),
        ),
    ]
