# Generated by Django 3.1.6 on 2021-02-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20210209_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('1', 'активний'), ('2', 'неактивний')], default='1', max_length=2, verbose_name='Статус'),
        ),
    ]
