# Generated by Django 3.1.6 on 2021-02-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_auto_20210210_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='students',
        ),
        migrations.AddField(
            model_name='lessons',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.group', verbose_name='Група'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.student', verbose_name='Учень'),
        ),
    ]
