# Generated by Django 3.1.6 on 2021-02-11 09:45

from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_auto_20210210_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(db_index=True, default=schedule.models.get_new_unique_invoice_number, max_length=100, unique=True, verbose_name='Унікальний номер рахунку'),
        ),
    ]
