# Generated by Django 3.1.6 on 2021-02-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_auto_20210211_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='receiver',
            field=models.CharField(choices=[('1', 'Школа'), ('2', 'Вчитель')], default='1', max_length=2, verbose_name='Отримувач'),
        ),
    ]
