# Generated by Django 3.1.6 on 2021-02-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_auto_20210212_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_presence', models.BooleanField(default=True, verbose_name='Був присутній?')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lessons', verbose_name='Заняття')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student', verbose_name='Учень')),
            ],
            options={
                'verbose_name': 'Відвідування',
                'verbose_name_plural': 'Відвідування',
            },
        ),
    ]
