# Generated by Django 3.1.6 on 2021-02-16 00:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_studentpresence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва заходу')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_of_event', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заходу')),
                ('time_start', models.TimeField(blank=True, default=None, null=True, verbose_name='Час початку(не обовʼязково)')),
                ('time_end', models.TimeField(blank=True, default=None, null=True, verbose_name='Час закінчення(не обовʼязково)')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.classroom', verbose_name='Аудиторія')),
                ('participants', models.ManyToManyField(to='schedule.Student', verbose_name='Учасники')),
            ],
            options={
                'verbose_name': 'Заходи',
                'verbose_name_plural': 'Заходи',
            },
        ),
    ]
