# Generated by Django 3.1.6 on 2021-02-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_auto_20210216_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentpresence',
            unique_together={('lessons', 'student')},
        ),
    ]
