# Generated by Django 3.1.7 on 2021-02-25 23:59

from django.db import migrations, models
import schedule.utils


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0032_auto_20210224_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.DateField(default=schedule.utils.datetime_now_tz, verbose_name='Дата заходу'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_test_lessons',
            field=models.DateTimeField(default=schedule.utils.datetime_now_tz, verbose_name='Дата тестового заняття'),
        ),
    ]
