# Generated by Django 3.1.7 on 2021-02-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0033_auto_20210226_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type_of',
            field=models.CharField(choices=[('1', 'індивідуальне'), ('2', 'групове')], max_length=2, null=True, verbose_name='Тип'),
        ),
    ]
