# Generated by Django 3.1.7 on 2021-02-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0034_service_type_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='lessons_count',
            field=models.IntegerField(verbose_name='К-сть занять'),
        ),
    ]
