# Generated by Django 3.1.7 on 2021-02-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0035_auto_20210226_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Дата старту роботи'),
        ),
    ]
