# Generated by Django 3.1.7 on 2021-03-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0036_teacher_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_valid_from',
            field=models.DateField(null=True, verbose_name='Дійсний з'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_valid_until',
            field=models.DateField(null=True, verbose_name='Дійсний по'),
        ),
    ]
