# Generated by Django 3.1.7 on 2021-03-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0038_auto_20210305_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_type',
            field=models.IntegerField(choices=[(1, 'індивідуальний'), (2, 'Груповий')], default=2, verbose_name='Тип аудиторії'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='receiver',
            field=models.IntegerField(choices=[(1, 'Школа'), (2, 'Вчитель')], verbose_name='Отримувач'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(1, 'оплачено'), (2, 'очікуємо оплати'), (3, 'закрито'), (4, 'тестове заняття')], verbose_name='Статус рахунку'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='lessons_type',
            field=models.IntegerField(choices=[(1, 'Індивідуальне'), (2, 'Групове')], verbose_name='Тип заняття'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_of',
            field=models.IntegerField(choices=[(1, 'Індивідуальний'), (2, 'Груповий')], null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, 'Активний'), (2, 'Неактивний'), (3, 'Тестовий')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.IntegerField(choices=[(1, 'Активний'), (2, 'Відпустка'), (3, 'Неактивний')], default=1, verbose_name='Статус'),
        ),
    ]
