# Generated by Django 3.1.7 on 2021-03-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0039_auto_20210305_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_type',
            field=models.IntegerField(choices=[(1, 'Індивідуальний'), (2, 'Груповий')], default=2, verbose_name='Тип аудиторії'),
        ),
    ]
