# Generated by Django 3.1.7 on 2021-03-08 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0040_auto_20210305_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date_when_should_pay',
            new_name='date_paid_until',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='receiver',
            field=models.IntegerField(choices=[(1, 'Школа'), (2, 'Вчитель')], null=True, verbose_name='Отримувач'),
        ),
        migrations.CreateModel(
            name='InvoiceStatusChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.IntegerField(choices=[(1, 'оплачено'), (2, 'очікуємо оплати'), (3, 'закрито'), (4, 'тестове заняття')])),
                ('new_status', models.IntegerField(choices=[(1, 'оплачено'), (2, 'очікуємо оплати'), (3, 'закрито'), (4, 'тестове заняття')])),
                ('datetime_created', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
