# Generated by Django 3.1.7 on 2021-03-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0041_auto_20210308_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicestatuschangelog',
            name='previous_status',
            field=models.IntegerField(choices=[(1, 'оплачено'), (2, 'очікуємо оплати'), (3, 'закрито'), (4, 'тестове заняття')], null=True),
        ),
    ]
