# Generated by Django 3.1.7 on 2021-03-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0042_auto_20210308_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lessons_color',
            field=models.CharField(blank=True, default='#269faf', max_length=10, null=True, verbose_name='Колір занять'),
        ),
    ]
