# Generated by Django 3.1.7 on 2021-03-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0044_invoicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
