# Generated by Django 3.1.7 on 2021-03-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0046_invoicestatuschangelog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.invoice'),
        ),
    ]
