# Generated by Django 3.1.7 on 2021-03-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0049_auto_20210314_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.invoice'),
        ),
    ]
