# Generated by Django 3.1.7 on 2021-03-16 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0050_auto_20210314_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='receiver_teacher',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.service', verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student', verbose_name='Студент'),
        ),
    ]
