# Generated by Django 3.1.7 on 2021-03-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0054_auto_20210320_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Додатково'),
        ),
    ]
