# Generated by Django 3.1.7 on 2021-03-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0055_auto_20210322_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='classroom',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=250, verbose_name='Локація'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessons',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classroom', verbose_name='Аудиторія'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.lessonsparent', verbose_name='Творець'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.student', verbose_name='Учень'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher', verbose_name='Викладач'),
        ),
    ]
