# Generated by Django 3.1.7 on 2021-03-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0057_auto_20210324_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='location',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
