# Generated by Django 3.1.7 on 2021-03-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0058_auto_20210324_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
