# Generated by Django 3.1.7 on 2021-03-29 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0060_auto_20210325_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='datetime_created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[(1, 'Активний'), (2, 'Видалено')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва предмету'),
        ),
    ]
