# Generated by Django 3.1.7 on 2021-04-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0063_auto_20210331_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='record_status',
            field=models.CharField(choices=[(1, 'Активний'), (2, 'Видалено')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='record_status',
            field=models.CharField(choices=[(1, 'Активний'), (2, 'Видалено')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.IntegerField(choices=[(1, 'Активний'), (2, 'Відпустка'), (3, 'Неактивний'), (4, 'Звільнений')], default=1, verbose_name='Статус'),
        ),
    ]
