# Generated by Django 3.2 on 2021-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0064_auto_20210405_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='record_status',
            field=models.IntegerField(choices=[(1, 'Активний'), (2, 'Видалено')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='record_status',
            field=models.IntegerField(choices=[(1, 'Активний'), (2, 'Видалено')], default=1, max_length=2),
        ),
    ]
