# Generated by Django 3.2 on 2021-04-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0065_auto_20210410_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='record_status',
            field=models.IntegerField(choices=[(1, 'Активний'), (2, 'Видалено')], default=1),
        ),
        migrations.AlterField(
            model_name='studentpresence',
            name='lessons',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.lessons', verbose_name='Заняття'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='record_status',
            field=models.IntegerField(choices=[(1, 'Активний'), (2, 'Видалено')], default=1),
        ),
    ]
